# Generated by Django 4.2.18 on 2025-01-29 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_title', models.CharField(blank=True, max_length=255, null=True)),
                ('item_sku', models.CharField(blank=True, max_length=255, null=True)),
                ('item_variant', models.CharField(blank=True, max_length=255, null=True)),
                ('item_quantity', models.IntegerField(blank=True, null=True)),
                ('item_price', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orderID', models.CharField(max_length=255, unique=True)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('item_count', models.IntegerField(blank=True, null=True)),
                ('shipping_price', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_method', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_status', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_code', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_type', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('total_discount_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('refunded_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('total_paid', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=255, null=True)),
                ('fulfillment_status', models.CharField(blank=True, max_length=255, null=True)),
                ('channel', models.CharField(blank=True, max_length=255, null=True)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at_shopify', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecretSurpriseOrders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_title', models.CharField(blank=True, max_length=255, null=True)),
                ('item_price', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_surprises', to='app.orderitems')),
            ],
        ),
        migrations.AddField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(db_column='OrderID', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='app.orders'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(db_column='OrderID', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='app.orders')),
            ],
        ),
    ]
