# Generated by Django 4.2.18 on 2025-01-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecretSurprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255)),
                ('item_title', models.CharField(max_length=255)),
                ('item_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopifyOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255)),
                ('order_date', models.DateTimeField()),
                ('item_count', models.IntegerField()),
                ('item_title', models.CharField(max_length=255)),
                ('item_sku', models.CharField(max_length=255)),
                ('item_variant', models.CharField(max_length=255)),
                ('item_quantity', models.IntegerField()),
                ('item_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('shipping_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('delivery_method', models.CharField(max_length=255)),
                ('delivery_status', models.CharField(max_length=255)),
                ('discount_code', models.CharField(max_length=255)),
                ('discount_type', models.CharField(max_length=255)),
                ('discount_amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('total_discount_amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('refunded_amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=4, max_digits=10)),
                ('payment_status', models.CharField(max_length=255)),
                ('fulfillment_status', models.CharField(max_length=255)),
                ('channel', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('customer_name', models.CharField(max_length=255)),
                ('shipping_address', models.TextField()),
                ('billing_address', models.TextField()),
                ('tracking_number', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
