# Generated by Django 4.2.18 on 2025-01-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_shopifyconnector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyorders',
            name='discount_amount',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shopifyorders',
            name='item_price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shopifyorders',
            name='refunded_amount',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shopifyorders',
            name='shipping_price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shopifyorders',
            name='total_discount_amount',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shopifyorders',
            name='total_paid',
            field=models.CharField(max_length=255),
        ),
    ]
