# Generated by Django 4.2.18 on 2025-01-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_shopifyorders_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretsurprise',
            name='item_price',
            field=models.CharField(max_length=255),
        ),
    ]
