# Generated by Django 4.2.18 on 2025-01-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer_created_at_customer_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='created_at_shopify',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
