# Generated by Django 4.2.18 on 2025-01-30 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_orders_created_at_shopify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='created_at_shopify',
        ),
    ]
