# Generated by Django 5.1.5 on 2025-01-27 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_secretsurprise_item_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyorders',
            name='updated_at_shopify',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
