# Generated by Django 4.2.18 on 2025-01-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_orders_created_at_shopify'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='store_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
