# Generated by Django 5.1.5 on 2025-01-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_shopifyorders_updated_at_shopify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyorders',
            name='updated_at_shopify',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
