# Generated by Django 4.2.18 on 2025-02-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_shopify_inventory_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyInventoryData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('product_title', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('product_type', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('collections', models.CharField(blank=True, max_length=255, null=True)),
                ('variant_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('variant_title', models.CharField(blank=True, max_length=255, null=True)),
                ('variant_sku', models.CharField(blank=True, max_length=255, null=True)),
                ('location_id', models.CharField(blank=True, max_length=255, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('available', models.IntegerField(default=0)),
                ('reserved', models.IntegerField(default=0)),
                ('incoming', models.IntegerField(default=0)),
                ('committed', models.IntegerField(default=0)),
                ('damaged', models.IntegerField(default=0)),
                ('on_hand', models.IntegerField(default=0)),
                ('quality_control', models.IntegerField(default=0)),
                ('safety_check', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='shopify_inventory_data',
        ),
    ]
