# Generated by Django 4.2.18 on 2025-02-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_shopifyinventorydata_delete_shopify_inventory_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyinventorydata',
            name='product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopifyinventorydata',
            name='variant_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
