# Generated by Django 4.2.18 on 2025-02-07 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_shopifyinventorydata_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyinventorydata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopifyinventorydata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
