# Generated by Django 4.2.18 on 2025-02-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_customer_billing_address_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyCampaign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('landing_site', models.TextField(blank=True, null=True)),
                ('cmp_id', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=255, null=True)),
                ('reffering_site', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='landing_site',
            field=models.TextField(blank=True, null=True),
        ),
    ]
