# Generated by Django 4.2.18 on 2025-02-11 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_shopifycampaign_alter_orders_landing_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopifycampaign',
            old_name='order_id',
            new_name='shopif_order_id',
        ),
        migrations.AddField(
            model_name='shopifycampaign',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='order_campaigns', to='app.orders'),
            preserve_default=False,
        ),
    ]
