# Generated by Django 4.2.18 on 2025-02-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_order_id_shopifycampaign_shopif_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='referring_site',
            field=models.TextField(blank=True, null=True),
        ),
    ]
