# Generated by Django 4.2.18 on 2025-02-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_orders_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifycampaign',
            name='campaign_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shopifycampaign',
            name='utm_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
