# Generated by Django 4.2.18 on 2025-02-20 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_shopifycampaign_campaign_id_shopifycampaign_utm_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
