# Generated by Django 4.2.18 on 2025-02-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_shopifyinventorydata_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyinventorydata',
            name='category',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopifyinventorydata',
            name='collections',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopifyinventorydata',
            name='variant_title',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
